FROM python:3.9-slim

RUN pip install poetry

RUN mkdir /app
WORKDIR /app
COPY poetry.lock pyproject.toml /app/

RUN poetry config virtualenvs.create false \
  && poetry install --no-interaction --no-ansi
CMD mkdir users_service
CMD mkdir tests
COPY ./api /app/api
COPY ./tests /app/tests

CMD python3 -m pytest ./tests

